headersOrigin = "inline"
redirectsOrigin = "inline"
functionsDirectory = "/workspace/0c85e0dc-1244-40ab-8f84-e11668f857da/sessions/agent_bb6a644a-d160-4d81-b13b-34a91515eb54/netlify/functions"
functionsDirectoryOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/workspace/0c85e0dc-1244-40ab-8f84-e11668f857da/sessions/agent_bb6a644a-d160-4d81-b13b-34a91515eb54/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/workspace/0c85e0dc-1244-40ab-8f84-e11668f857da/sessions/agent_bb6a644a-d160-4d81-b13b-34a91515eb54/netlify/functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]